"""initial schema

Revision ID: 98e07fd05c9e
Revises: 
Create Date: 2026-09-06 13:54:10.129234+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import apps.api.db  # JSONType / EmbeddingType 등 커스텀 타입


revision = '98e07fd05c9e'
down_revision = None
branch_labels = None
depends_on = None


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    # pgvector는 vector 컬럼을 만들기 전에 준비되어야 한다(제3.2장).
    if _is_postgres():
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('document_id', sa.String(length=40), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=True),
    sa.Column('payload', apps.api.db.JSONType(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash')
    )
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('forced_ai_policy', sa.String(length=20), nullable=True),
    sa.Column('blocked_providers', apps.api.db.JSONType(), nullable=True),
    sa.Column('block_sealed_reveal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('case_number', sa.String(length=80), nullable=True),
    sa.Column('court', sa.String(length=120), nullable=True),
    sa.Column('case_type', sa.String(length=40), nullable=True),
    sa.Column('parties', apps.api.db.JSONType(), nullable=True),
    sa.Column('incident_date', sa.String(length=20), nullable=True),
    sa.Column('key_dates', apps.api.db.JSONType(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('tags', apps.api.db.JSONType(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('external_ai_policy', sa.String(length=20), nullable=True),
    sa.Column('verification_profile', sa.String(length=20), nullable=True),
    sa.Column('enabled_advisory_signals', apps.api.db.JSONType(), nullable=True),
    sa.Column('requested_issues', apps.api.db.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('document_kind', sa.String(length=60), nullable=True),
    sa.Column('is_own_document', sa.Boolean(), nullable=True),
    sa.Column('quarantined', sa.Boolean(), nullable=True),
    sa.Column('rag_indexable', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('data', apps.api.db.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    op.create_table('verification_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('document_ids', apps.api.db.JSONType(), nullable=True),
    sa.Column('profile', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('stage_message', sa.String(length=300), nullable=True),
    sa.Column('verification_key', sa.String(length=64), nullable=True),
    sa.Column('scores', apps.api.db.JSONType(), nullable=True),
    sa.Column('timeline', apps.api.db.JSONType(), nullable=True),
    sa.Column('unavailable_sources', apps.api.db.JSONType(), nullable=True),
    sa.Column('unverified_items', apps.api.db.JSONType(), nullable=True),
    sa.Column('errors', apps.api.db.JSONType(), nullable=True),
    sa.Column('result_json', apps.api.db.JSONType(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_runs_verification_key'), 'verification_runs', ['verification_key'], unique=False)
    op.create_table('api_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('adapter', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['verification_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('data', apps.api.db.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('data', apps.api.db.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_blocks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('bbox', apps.api.db.JSONType(), nullable=True),
    sa.Column('source_layer', sa.String(length=30), nullable=True),
    sa.Column('block_type', sa.String(length=30), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('attributes', apps.api.db.JSONType(), nullable=True),
    sa.Column('embedding', apps.api.db.EmbeddingType(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_pages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('attributes', apps.api.db.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=True),
    sa.Column('data', apps.api.db.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('evidence_grade', sa.String(length=4), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('engine', sa.String(length=60), nullable=True),
    sa.Column('meta_message_type', sa.String(length=10), nullable=True),
    sa.Column('advisory_only', sa.Boolean(), nullable=True),
    sa.Column('tags', apps.api.db.JSONType(), nullable=True),
    sa.Column('data', apps.api.db.JSONType(), nullable=True),
    sa.Column('sealed_excerpt', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=40), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['verification_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index(op.f('ix_findings_type'), 'findings', ['type'], unique=False)
    op.create_table('model_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('quarantined', sa.Boolean(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['verification_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('formats', apps.api.db.JSONType(), nullable=True),
    sa.Column('artifacts', apps.api.db.JSONType(), nullable=True),
    sa.Column('include_sealed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['verification_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('adapter', sa.String(length=60), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_id', sa.String(length=200), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('used_fields', apps.api.db.JSONType(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['verification_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('detail', apps.api.db.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['verification_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('finding_id', sa.String(length=40), nullable=False),
    sa.Column('data', apps.api.db.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_artifacts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('report_id', sa.String(length=40), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('storage_key', sa.String(length=400), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


    # --- 운영 인덱스 (자동 생성 대상 아님) ---
    if _is_postgres():
        # 임베딩 근사 최근접 검색 (제3.2장 pgvector)
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_document_blocks_embedding_hnsw "
            "ON document_blocks USING hnsw (embedding vector_cosine_ops)"
        )
        # Finding 필터(제19.3장)에서 자주 쓰는 조합
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_findings_project_severity "
            "ON findings (project_id, severity, review_status)"
        )
        # 감사추적은 append-only이므로 UPDATE·DELETE를 트리거로 차단한다(부록 C 제7항).
        op.execute(
            """
            CREATE OR REPLACE FUNCTION audit_events_append_only() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_events는 append-only이다: % 는 허용되지 않는다', TG_OP;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            "CREATE TRIGGER audit_events_no_update_delete "
            "BEFORE UPDATE OR DELETE ON audit_events "
            "FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()"
        )


def downgrade() -> None:
    if _is_postgres():
        op.execute("DROP TRIGGER IF EXISTS audit_events_no_update_delete ON audit_events")
        op.execute("DROP FUNCTION IF EXISTS audit_events_append_only()")
        op.execute("DROP INDEX IF EXISTS ix_findings_project_severity")
        op.execute("DROP INDEX IF EXISTS ix_document_blocks_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_artifacts')
    op.drop_table('evidence')
    op.drop_table('verification_checks')
    op.drop_table('source_records')
    op.drop_table('reports')
    op.drop_table('model_executions')
    op.drop_index(op.f('ix_findings_type'), table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('events')
    op.drop_table('document_versions')
    op.drop_table('document_pages')
    op.drop_table('document_blocks')
    op.drop_table('claims')
    op.drop_table('citations')
    op.drop_table('api_executions')
    op.drop_index(op.f('ix_verification_runs_verification_key'), table_name='verification_runs')
    op.drop_table('verification_runs')
    op.drop_table('project_members')
    op.drop_table('entities')
    op.drop_table('documents')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
